version: docker-version

services:
  db:
    build:
      context: .
      dockerfile: dockerfile.mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./src/db-scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
    ports:
      - 3306:3306
    restart: always
    secrets:
      - db_root_password
      - db_user
      - db_password
      - db_name

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile.backend
#    ports:
#      - "3000:3000"
#    depends_on:
#      - mysql

volumes:
  db_data:

secrets:
  db_password:
    file: docker-secrets/db_password.txt
  db_root_password:
    file: docker-secrets/db_root_password.txt
  db_name:
    file: docker-secrets/db_name.txt
  db_user:
    file: docker-secrets/db_user.txt
