version: docker-version

secrets:
  db_password:
    file: docker-secrets/db_password.txt
  db_root_password:
    file: docker-secrets/db_root_password.txt
  db_name:
    file: docker-secrets/db_name.txt
  db_user:
    file: docker-secrets/db_user.txt

volumes:
  db_data:

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: /run/secrets/db_name
      MYSQL_USER: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 3306:3306
    restart: always
    secrets:
      - db_root_password
      - db_password
      - db_name
      - db_user

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile.backend
#    ports:
#      - "3000:3000"
#    depends_on:
#      - mysql
